node_id = 1
http_addr = "127.0.0.1:8001"

[raft]
addr = "127.0.0.1:7001"
single = false
join = ["127.0.0.1:7002", "127.0.0.1:7003"]

[rocksdb]
data_path = "/tmp/rockraft_cluster/node1"
max_open_files = 10000
