node_id = 2
http_addr = "127.0.0.1:8002"

[raft]
address = "127.0.0.1:7002"
advertise_host = "localhost"
single = false
join = ["localhost:7001", "localhost:7002", "localhost:7003"]

[rocksdb]
data_path = "/tmp/rockraft_cluster/node2"
max_open_files = 10000

[log]
file = "/tmp/rockraft_cluster/logs/node2.log"
level = "info"
