node_id = 3
http_addr = "127.0.0.1:8003"

[raft]
address = "127.0.0.1:7003"
advertise_host = "localhost"
single = false
join = ["localhost:7001", "localhost:7002", "localhost:7003"]

[rocksdb]
data_path = "/tmp/rockraft_cluster/node3"
max_open_files = 10000

[log]
file = "/tmp/rockraft_cluster/logs/node3.log"
level = "info"
