node_id = 3
http_addr = "127.0.0.1:8003"

[raft]
address = "127.0.0.1:7003"
advertise_host = "localhost"
single = false
join = ["127.0.0.1:7001"]

[rocksdb]
data_path = "/tmp/rockraft_cluster/node3"
max_open_files = 10000

[log]
file = ".rockraft_data/node3.log"
level = "info"
