node_id = 1
http_addr = "127.0.0.1:8001"

[raft]
address = "127.0.0.1:7001"
advertise_host = "localhost"
single = true
join = []

[rocksdb]
data_path = "/tmp/rockraft_cluster/node1"
max_open_files = 10000

[log]
file = ".rockraft_data/node1.log"
level = "info"
